### ISSUE TITLE
Add option to toogle the wrap guide

### ISSUE THREAD

**Issue by thedaniel** [atom/wrap-guide#50] opened 2015-10-29 12:52 UTC
_From @arcticicestudio on October 29, 2015 9:57_

I don't know if this belongs here or into the [specific repositiory](https://github.com/atom/wrap-guide).
It would be nice if the [wrap-guide](https://atom.io/packages/wrap-guide) package could be toggled via Command Palette or menu (_Edit_ -> _Toggle Wrap Guide_).
I've disabled the package because it bothers me, but sometimes I need it.
Actually you have to navigate to the settings view, search for the wrap-guide package and enable/disable it all the time.

_Copied from original issue: atom/atom#9330_

**Comment by thomasjo** [comment] 2015-10-29 19:43
I have an open PR for this https://github.com/atom/wrap-guide/pull/39. Just never got around to merging it. Although I'm not sure if we want it to be a "persisted" toggle like it is now, or if we want it to behave more like the *Toggle Soft Wrap* option.

**Comment by 50Wliu** [comment] 2017-11-28 22:59
Closing as a duplicate of #28.

**Closed by 50Wliu** 2017-11-28 22:59 UTC
Labels: enhancement
