### ISSUE TITLE
Changes to preferred line length have no effect if a file has already been opened

### ISSUE THREAD

**Issue by WalterGR** [atom/wrap-guide#51] opened 2016-01-01 21:32 UTC
Atom 1.3.2 on OS X 10.10.5.

Repro steps:
1. Open a folder in Atom from the command line via `atom .`
2. Have the "Preferred line length" set to `x` characters.
3. Open one or more files.
4. Change the "Preferred line length" to `y` characters.

Expected:

The wrap guide is moved to the new position in open file(s).

Actual:

In open file(s), the wrap guide is still displayed at its old position.

Additionally, the following techniques do not work to move the wrap guide to the new location:
-  Executing the "Window: Reload" command.
-  Closing the editor tab for a file, right-clicking a still-open tab, and selecting "Reopen closed tab".
-  Closing the editor tab for a file and re-opening the file from the treeview.
-  Exiting Atom completely and re-starting.
-  Exiting Atom completely and re-starting in safe mode.

**Comment by lee-dohm** [comment] 2016-01-02 00:08
I cannot reproduce this using Atom v1.3.2 on Mac OS X 10.11.2:

![wrap-guide](https://cloud.githubusercontent.com/assets/1038121/12072681/b8ab260a-b0a1-11e5-8e7d-05111bf9ab85.gif)

Can you reproduce the issue in Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by WalterGR** [comment] 2016-01-02 05:35
Did you perform step 1?  (It's not shown in the GIF so I don't know.)

When you say "Can you reproduce this issue in Safe Mode?" did you see that I wrote "Additionally, the following techniques do not work to move the wrap guide to the new location...   Exiting Atom completely and re-starting in safe mode."?

If you did see it, do you mean that you want me to try all of the repro steps in safe mode?

**Comment by WalterGR** [comment] 2016-01-02 06:01
Closing.

I was seeing it repro in Clojure source files.  `preferredLineLenth` was overridden in the settings for the `language-clojure` package to be `x`, which explains why setting it to `y` in the core Settings had no effect.

While I don't remember ever setting a line length specifically for Clojure (why would I?), I can't guarantee 100% that I did not.

**Comment by dcalhoun** [comment] 2016-04-25 21:10
Manually unsetting each language package's preferred line length fixed the issue for me too. Is it possible that at some point, potentially during an Atom upgrade, that language specific settings were automatically set by Atom (i.e. – copied from the my global setting)? I'm fairly confident I never set individual language line length preferences.

**Comment by WalterGR** [comment] 2016-04-25 23:05
Could be.  Reopening to gather more information.

**Comment by lee-dohm** [comment] 2016-04-26 00:28
If preferredLineLength settings are being copied from the global to language-specific settings, a new Issue should be opened. It should probably be opened either on atom/atom or atom/settings-view depending on the source of the problem.

**Comment by 50Wliu** [comment] 2017-11-28 22:57
Closing as this is not an issue with wrap-guide.  If you do experience global settings being copied to language-specific settings, please follow Lee's suggestions and open a new issue on atom/atom or atom/settings-view so that we can triage it further.

**Closed by 50Wliu** 2017-11-28 22:57 UTC
Labels: more-information-needed, needs-reproduction
